# render.yaml
services:
  - type: web
    name: render-tailscale-web
    env: docker
    autoDeploy: false
    port: 8080
    healthCheckPath: /
    envVars:
      - key: TAILSCALE_AUTHKEY
        sync: false
      - key: TAILSCALE_VERSION
        value: "1.82.5"
      - key: ADVERTISE_ROUTES
        value: "10.0.0.0/8"
    disk:
      name: tailscale-state
      mountPath: /var/lib/tailscale
      sizeGB: 1
